deployment:
  kong:
    enabled: true

env:
  database: "off"
  router_flavor: traditional
  log_level: info

  admin_listen: "0.0.0.0:8001"
  admin_gui_listen: "0.0.0.0:8002"

  admin_gui_url: http://admin.kong.local
  admin_gui_api_url: https://kong-kong-admin.kong.svc.cluster.local:8001

ingressController:
  enabled: true
  installCRDs: false
  ingressClass: kong

  env:
    kong_admin_url: http://kong-kong-admin.kong.svc.cluster.local:8001
    kong_admin_tls_skip_verify: true

proxy:
  enabled: true
  type: ClusterIP

  http:
    enabled: true
    servicePort: 80

  tls:
    enabled: false

admin:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001
  tls:
    enabled: false

manager:
  enabled: true
  type: ClusterIP