apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: relationship-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/agifsofyan/tomodachi-relationship-service.git
    targetRevision: main
    path: kubernetes/relationship-service
  destination:
    server: https://kubernetes.default.svc
    namespace: tomodachi-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
