apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: tomodachi-app
type: Opaque
stringData:
  DATABASE_URL: "postgresql+psycopg://agifsofyan:11234567777@localhost:5432/tomodachi"
  SECRET_KEY: "supersecretkey"