apiVersion: v1
kind: Secret
metadata:
  name: relationship-service-secret
  namespace: tomodachi-app
type: Opaque
stringData:
  DATABASE_USER: "agifsofyan"
  DATABASE_PASSWORD: "11234567777"
  JWT_SECRET_KEY: "supersecretkey"